vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
        usedCar:
            uri_prefix: public/images/usedCar
            upload_destination: '%kernel.project_dir%/public/images/usedCar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


