CREATE TABLE testimonial
(id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
content LONGTEXT NOT NULL,
note INT NOT NULL)

CREATE TABLE used_car
(id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(150) NOT NULL,
price DOUBLE NOT NULL,
year INT NOT NULL, kilometer INT NOT NULL,
caracteristics LONGTEXT NOT NULL,
energy VARCHAR(100) NOT NULL,
image VARCHAR(255) NOT NULL)

CREATE TABLE user
(id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
email VARCHAR(180) NOT NULL,
roles JSON NOT NULL,
password VARCHAR(255) NOT NULL)

ALTER TABLE testimonial ADD email VARCHAR(255) NOT NULL

ALTER TABLE testimonial ADD approved TINYINT(1) NOT NULL

CREATE TABLE contact 
(id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
first_name VARCHAR(100) NOT NULL, 
last_name VARCHAR(100) NOT NULL, 
email VARCHAR(255) NOT NULL, 
phone_number VARCHAR(15) NOT NULL, 
content LONGTEXT NOT NULL)

ALTER TABLE contact ADD approved TINYINT(1) NOT NULL

CREATE TABLE services 
(id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
name VARCHAR(255) NOT NULL, 
content LONGTEXT NOT NULL)

ALTER TABLE services ADD images VARCHAR(255) NOT NULL

CREATE TABLE address 
(id INT AUTO_INCREMENT NOT NULL PRIMARY KEY , 
street VARCHAR(150) NOT NULL, 
city VARCHAR(100) NOT NULL, 
zip_code VARCHAR(100) NOT NULL)

CREATE TABLE opening_days 
(id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
days VARCHAR(50) NOT NULL, 
open VARCHAR(100) NOT NULL)

ALTER TABLE address ADD phone_number VARCHAR(20) NOT NULL

ALTER TABLE used_car ADD image_name VARCHAR(255) NOT NULL, CHANGE image image_file VARCHAR(255) NOT NULL

ALTER TABLE used_car CHANGE image_name image_name VARCHAR(255) DEFAULT NULL

ALTER TABLE used_car CHANGE image_file image VARCHAR(255) NOT NULL

ALTER TABLE used_car DROP image

CREATE TABLE image 
(id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
image_name VARCHAR(255) NOT NULL)

ALTER TABLE used_car DROP image_name

ALTER TABLE used_car CHANGE image_file image VARCHAR(255) NOT NULL

ALTER TABLE testimonial DROP email

ALTER TABLE testimonial ADD email VARCHAR(255) NOT NULL

ALTER TABLE used_car ADD contact_id INT DEFAULT NULL

ALTER TABLE used_car ADD FOREIGN KEY (contact_id) REFERENCES contact (id)