controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
favicon:
    path: /favicon.ico
    controller: App\Controller\FaviconController::serveFavicon
